// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lcfsuhdcexrbqevdojlw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxjZnN1aGRjZXhyYnFldmRvamx3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4MjE5NDEsImV4cCI6MjA3MTM5Nzk0MX0.m6xnZa5I6w32IznLUt1xUYllFIiRcuv0574QLAXkq18";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});